const CACHE_NAME='guanxiang-shell-v53';
const SHELL=['./','./index.html','./auth.html','./support.html','./changelog.html','./pro.html','./disclaimer.html','./privacy.html','./feedback.html','./report.html','./styles.css','./auth.css','./info.css','./landing-v2.css','./landing-rich.css','./landing-details.css','./app.js','./auth.js','./info.js','./info-content.mjs','./i18n.mjs','./hexagram-i18n.mjs','./hexagram-catalog.mjs','./daily-hexagram.mjs','./yarrow-core.mjs','./reading-rules.mjs','./interpretation.mjs','./ai-reading.mjs','./ai-sources.mjs','./derived-hexagrams.mjs','./liuyao-core.mjs','./liuyao-rules.mjs','./sexagenary.mjs','./vendor/lunar-javascript/lunar.js','./study-storage.mjs','./storage.mjs','./account-sync.mjs','./ten-wings.json','./hexagram-texts.json','./principles.json','./principles-en.json','./relations.json','./manifest.webmanifest','./app-icon.svg','./html-safety.mjs','./service-worker-update.mjs'];
const STATIC_PAGE_FALLBACKS=new Map([['/support','./support.html'],['/changelog','./changelog.html'],['/pro','./pro.html'],['/disclaimer','./disclaimer.html'],['/privacy','./privacy.html'],['/feedback','./feedback.html'],['/report','./report.html']]);
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE_NAME).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
async function fetchAndCache(request){const response=await fetch(request);if(response.ok&&new URL(request.url).origin===self.location.origin){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy))}return response}
function navigationFallback(pathname){const normalized=pathname.length>1?pathname.replace(/\/$/,''):pathname;if(STATIC_PAGE_FALLBACKS.has(normalized))return STATIC_PAGE_FALLBACKS.get(normalized);if(normalized==='/auth'||normalized==='/auth.html')return './auth.html';return './index.html'}
async function navigationResponse(request){try{return await fetchAndCache(request)}catch{const cached=await caches.match(request);if(cached)return cached;return await caches.match(navigationFallback(new URL(request.url).pathname))||Response.error()}}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;if(event.request.mode==='navigate'){event.respondWith(navigationResponse(event.request));return}event.respondWith(caches.match(event.request).then(cached=>cached||fetchAndCache(event.request).catch(()=>Response.error())))});
self.addEventListener('message',event=>{if(event.data==='SKIP_WAITING')self.skipWaiting()});
