import assert from 'node:assert/strict';
import { backupStatus, mergeJournalRecords, migrateJournalPayload, normalizeAiReading } from './storage.mjs';
import { deleteAnnotation, loadAnnotations, saveAnnotation } from './study-storage.mjs';
const makeStorage = () => { const map = new Map(); return { getItem: key => map.get(key) || null, setItem: (key, value) => map.set(key, value), removeItem: key => map.delete(key) }; };
const line = { value: 7, changes: [{ before: 49, left: 24, right: 25, rightAfter: 24, leftR: 1, rightR: 3, removed: 5, remaining: 44 }, { before: 44, left: 20, right: 24, rightAfter: 23, leftR: 4, rightR: 3, removed: 8, remaining: 36 }, { before: 36, left: 16, right: 20, rightAfter: 19, leftR: 4, rightR: 3, removed: 8, remaining: 28 }] };
const record = (id, updatedAt, note = '') => ({ id, question: '一个具体的问题', lines: Array(6).fill(line), originalIndex: 0, changedIndex: 0, note, completedAt: updatedAt, updatedAt });
const migrated = migrateJournalPayload([record('a', '2026-01-01T00:00:00.000Z')]);
assert.equal(migrated.version, 2);
assert.equal(migrated.records[0].reviewState, '未开始');
assert.equal(mergeJournalRecords(migrated.records, [record('a', '2026-02-01T00:00:00.000Z', '较新的札记')])[0].note, '较新的札记');
assert.equal(backupStatus(Array(20).fill(record('x', '2026-01-01T00:00:00.000Z'))).due, true);
const aiReading={text:'【核心判断】\n宜先辨明条件。',generatedAt:'2026-09-11T08:00:00.000Z',modelLabel:'Workers AI',version:1};
const migratedAi=migrateJournalPayload([{...record('ai','2026-09-11T08:00:00.000Z'),aiReading}]);
assert.equal(migratedAi.records[0].aiReading.text,aiReading.text);
assert.equal(normalizeAiReading({text:'',generatedAt:'bad',modelLabel:'x',version:1}),null);
assert.equal(normalizeAiReading({...aiReading,text:'甲'.repeat(13000)}).text.length,12000);
const invalidAi=migrateJournalPayload([{...record('invalid-ai','2026-09-11T08:00:00.000Z'),aiReading:{text:''}}]);
assert.equal(Object.hasOwn(invalidAi.records[0],'aiReading'),false);
const mergedAi=mergeJournalRecords([record('merge-ai','2026-09-11T08:00:00.000Z')],[{...record('merge-ai','2026-09-11T08:00:00.000Z'),aiReading}]);
assert.equal(mergedAi[0].aiReading.text,aiReading.text);
const storage = makeStorage();
const annotation = saveAnnotation({ sourceType: 'hexagram', sourceId: '0', note: '记录一个观察', tags: ['复习'] }, storage);
assert.equal(loadAnnotations(storage).length, 1);
deleteAnnotation(annotation.id, storage);
assert.equal(loadAnnotations(storage).length, 0);
console.log('Storage migration, merge, backup, and annotation tests passed.');
